version: '3.9'

services:

  mongo_db:
    container_name: db_container
    image: mongo:latest
    restart: always
    volumes:
      - mongo_db:/data/db
  api:
    build: .
    ports:
    - 4848:4848
    environment:
      PORT: 4848
      MONGODB_URI: mongodb://mongo_db:27017
      DB_NAME: my_db
      NAME: Test
    depends_on:
      - mongo_db
  
volumes:
  mongo_db: {}
